import React, { useState, useContext } from "react";
import { useParams } from "react-router-dom";
import { UserContext } from "../../contexts/user.context";
import { collection, addDoc, serverTimestamp, doc } from "firebase/firestore";
import { db } from "../../utils/firebase/firebase.utils";

const ProposalForm = () => {
  const { currentUser } = useContext(UserContext);
  const { jobId } = useParams();
  const [proposalData, setProposalData] = useState({
    description: "",
    price: "",
    deliveryTime: "",
  });

  const handleSubmit = async (event) => {
    event.preventDefault();

    try {
      const proposalRef = await addDoc(collection(db, "proposals"), {
        jobId,
        userId: currentUser.uid,
        ...proposalData,
        createdAt: serverTimestamp(),
      });

      const proposalId = proposalRef.id; // Get the unique id generated by Firestore

      console.log("Proposal submitted successfully!");
      setProposalData({
        description: "",
        price: "",
        deliveryTime: "",
      });
    } catch (error) {
      console.error("Error submitting proposal", error);
    }
  };

  const handleChange = (event) => {
    const { name, value } = event.target;
    setProposalData({ ...proposalData, [name]: value });
  };

  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor="description">Description:</label>
      <textarea
        id="description"
        name="description"
        value={proposalData.description}
        onChange={handleChange}
      />

      <label htmlFor="price">Price:</label>
      <input
        type="number"
        id="price"
        name="price"
        value={proposalData.price}
        onChange={handleChange}
      />

      <label htmlFor="deliveryTime">Delivery Time:</label>
      <input
        type="number"
        id="deliveryTime"
        name="deliveryTime"
        value={proposalData.deliveryTime}
        onChange={handleChange}
      />

      <button type="submit">Submit Proposal</button>
    </form>
  );
};

export default ProposalForm;
